import { defineConfig } from "tsup";

export default defineConfig({
    entry: [
        "src/vite/ssr/index.ts",
        "src/vite/plugin/index.ts",
        "src/react/link.tsx",
        "src/react/index.tsx",
        "src/react/head.tsx",
        "src/react/document.tsx",
        "src/react/auth.tsx",
        "src/react/router/index.tsx",
        "src/react/server.tsx",
        "src/react/client.tsx",
        "src/react/routes.tsx",
        "src/react/intl.ts",
        "src/react/cookies.tsx",
    ],
    external: [
        'react-helmet-async',
        'virtual:reacticajs:context:Router',
        'virtual:reacticajs:side-effect',
        '$output/reactica-manifest.json',
        'virtual:reacticajs:context:AmpState',
        'virtual:reacticajs:context:HeadManager',
        '~react-pages',
        'virtual:reacticajs:context',
        'virtual:reacticajs:router-context',
        'virtual:reacticajs:cookies-context',
        'virtual:reacticajs:html-context',
        'virtual:reacticajs:auth-context',
        'react-router',
        'react-router-dom',
        'react-intl',
        'virtual:reacticajs:pages-parsed',
        'virtual:reacticajs:pages-sync',
        'virtual:reacticajs:pages-async',
        "virtual:reacticajs:server",
        "virtual:generated-pages",
        "virtual:reacticajs:servers",
        "virtual:reacticajs:server-hooks",
        "virtual:reacticajs:client-hooks",
        "virtual:reacticajs:common-hooks",
        "virtual:reacticajs:page-imports",
        "virtual:reacticajs:api-imports",
        "virtual:reacticajs:placeholder",
    ],
    outDir: "dist",
    format: ["esm", "cjs"],
    dts: true,
    clean: true,
    target: "esnext",
    shims: false,
});
