import { defineConfig } from "tsup";

export default defineConfig({
    entry: [
        // "src/pages/index.ts",
        "src/vite/index.ts",
        "src/vite/plugin/index.ts",
        "src/link.tsx",
        "src/index.tsx",
        "src/head.tsx",
        "src/document.tsx",
        "src/auth.tsx",
        "src/router.tsx",
        "src/server.tsx",
        "src/client.tsx",
        "src/routes.tsx",
        "src/cookies.tsx",
        // "src/placeholder-loader.tsx",
    ],
    external: [
        'react-helmet-async',
        'virtual:reacticajs:context:Router',
        'virtual:reacticajs:side-effect',
        '$output/reactica-manifest.json',
        'virtual:reacticajs:context:AmpState',
        'virtual:reacticajs:context:HeadManager',
        '~react-pages',
        'virtual:reacticajs:context',
        'virtual:reacticajs:cookies-context',
        'virtual:reacticajs:html-context',
        'virtual:reacticajs:auth-context',
        'react-router',
        'react-router-dom',
        'virtual:reacticajs:pages-parsed',
        'virtual:reacticajs:pages-sync',
        'virtual:reacticajs:pages-async',
        "virtual:reacticajs:server",
        "virtual:generated-pages",
        "virtual:reacticajs:servers",
        "virtual:reacticajs:server-hooks",
        "virtual:reacticajs:client-hooks",
        "virtual:reacticajs:common-hooks",
        "virtual:reacticajs:page-imports",
        "virtual:reacticajs:api-imports",
        "virtual:reacticajs:placeholder",
    ],
    outDir: "dist",
    format: ["esm", "cjs"],
    dts: true,
    clean: true,
    target: "esnext",
    shims: false,
});