import { defineConfig } from "tsup";

export default defineConfig({
    entry: [
        "src/plugin/index.ts",
        "src/react/link.tsx",
        "src/react/index.tsx",
        "src/react/client.tsx",
        "src/react/routes.tsx",
        "src/react/router/index.tsx",
        "src/react/auth/index.tsx",
        "src/react/cookies.tsx",
        "src/react/intl.ts",
        "src/react/document.tsx",
        "src/react/server.tsx",
        "src/server/index.ts",
        // "src/react/index.tsx",
        // "src/react/head.tsx",
        // "src/react/server.tsx",
        // "src/react/intl.ts",
    ],
    external: [
        'react',
        'react-dom',
        'virtual:reactica:pages-async',
        'virtual:reactica:pages-sync',
        'virtual:reactica:context',
        'virtual:reactica:context:cookies',
        'virtual:reactica:context:router',
        'virtual:reactica:context:auth',
        'virtual:reactica:context:html',
        'react-router-dom',
        'react-router',
        'react-intl',

        // 'react-helmet-async',
        // 'virtual:reacticajs:context:Router',
        // 'virtual:reacticajs:side-effect',
        // '$output/reactica-manifest.json',
        // 'virtual:reacticajs:context:AmpState',
        // 'virtual:reacticajs:context:HeadManager',
        // '~react-pages',
        // 'virtual:reacticajs:router-context',
        // 'virtual:reacticajs:cookies-context',
        // 'virtual:reacticajs:html-context',
        // 'virtual:reacticajs:auth-context',
        // 'react-router',
        // 'react-intl',
        // 'virtual:reacticajs:pages-parsed',
        // 'virtual:reacticajs:pages-sync',
        // 'virtual:reacticajs:pages-async',
        // "virtual:reacticajs:server",
        // "virtual:generated-pages",
        // "virtual:reacticajs:servers",
        // "virtual:reacticajs:server-hooks",
        // "virtual:reacticajs:client-hooks",
        // "virtual:reacticajs:common-hooks",
        // "virtual:reacticajs:page-imports",
        // "virtual:reacticajs:api-imports",
        // "virtual:reacticajs:placeholder",
    ],
    outDir: "dist",
    format: ["esm", "cjs"],
    dts: true,
    clean: true,
    target: "esnext",
    shims: false,
});
